baseURL = 'https://localglobal.study/'
languageCode = 'en-us'
title = 'LocalGlobal'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  mainSections = ["posts", "essays"]

  [params.homeInfoParams]
    Title = "Local-Global"
    Content = "Exploring the mathematics, philosophy, and ecological economics of civilisational design. In particular, pondering what shared ends we, as a collection of agents in a shared world, ought to pursue, and what physical reality permits."

  [[params.socialIcons]]
    name = "email"
    url = "mailto:schultzchristian@outlook.com"
