baseURL = 'https://localglobal.study/'
languageCode = 'en-us'
title = 'LocalGlobal'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  mainSections = ["posts", "essays"]

  [params.homeInfoParams]
    Title = "Local-Global"
    Content = "Exploring the mathematics, philosophy, and ecological economics of civilisational design. In particular, pondering what shared ends we, as a collection of agents in a shared world, ought to pursue, and what physical reality permits."

  [[params.socialIcons]]
    name = "email"
    url = "mailto:localglobal@protonmail.com"

[[menu.main]]
  name = "Essays"
  url = "/essays/"
  weight = 10

[[menu.main]]
  name = "Crises"
  url = "/crises/"
  weight = 20

[[menu.main]]
  name = "Local Solutions"
  url = "/local-solutions/"
  weight = 30

[[menu.main]]
  name = "Global Solutions"
  url = "/global-solutions/"
  weight = 40

[[menu.main]]
  name = "Domains"
  url = "/domains/"
  weight = 50

[[menu.main]]
  name = "Mathematics"
  url = "/mathematics/"
  weight = 60

[[menu.main]]
  name = "Notation"
  url = "/notation/"
  weight = 70

[[menu.main]]
  name = "Library"
  url = "/library/"
  weight = 80

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 90
